n=int(input('So tien ban dau: '))
k=int(input('So thang gui: '))
T=float(input('Lai suat/thang: '))
m=n*(1+k*T)
print('Voi so tien ban dau ',n,',',sep='',end='')
print(' sau',k,'thang gui,',end='')
print(' lai suat ',T,'/',sep='',end='')
print(' thang')
print('Thi so tien nhan duoc cuoi ky la:',m)